### ISSUE TITLE
Help building on MacOS?

### ISSUE THREAD

**Issue by thom-nic** [morgadow/gocan#1]
I'm a golang novice and I'd like to make a basic CLI app to send some CAN frames from MacOS using a PCAN USB adapter.

When I add this module in a new project and attempt to build using go 1.23 I get a bunch of errors:
```
± go build   
# github.com/morgadow/gocan/interfaces/pcan
/Users/thom/go/pkg/mod/github.com/morgadow/gocan@v1.1.4/interfaces/pcan/pcanBus.go:205:20: undefined: syscall.Handle
/Users/thom/go/pkg/mod/github.com/morgadow/gocan@v1.1.4/interfaces/pcan/pcanBasic.go:16:28: undefined: syscall.DLL
/Users/thom/go/pkg/mod/github.com/morgadow/gocan@v1.1.4/interfaces/pcan/pcanBasic.go:17:32: undefined: syscall.Proc
/Users/thom/go/pkg/mod/github.com/morgadow/gocan@v1.1.4/interfaces/pcan/pcanBasic.go:18:34: undefined: syscall.Proc
/Users/thom/go/pkg/mod/github.com/morgadow/gocan@v1.1.4/interfaces/pcan/pcanBasic.go:19:34: undefined: syscall.Proc
/Users/thom/go/pkg/mod/github.com/morgadow/gocan@v1.1.4/interfaces/pcan/pcanBasic.go:20:27: undefined: syscall.Proc
/Users/thom/go/pkg/mod/github.com/morgadow/gocan@v1.1.4/interfaces/pcan/pcanBasic.go:21:31: undefined: syscall.Proc
/Users/thom/go/pkg/mod/github.com/morgadow/gocan@v1.1.4/interfaces/pcan/pcanBasic.go:22:26: undefined: syscall.Proc
/Users/thom/go/pkg/mod/github.com/morgadow/gocan@v1.1.4/interfaces/pcan/pcanBasic.go:23:28: undefined: syscall.Proc
/Users/thom/go/pkg/mod/github.com/morgadow/gocan@v1.1.4/interfaces/pcan/pcanBasic.go:24:27: undefined: syscall.Proc
/Users/thom/go/pkg/mod/github.com/morgadow/gocan@v1.1.4/interfaces/pcan/pcanBasic.go:24:27: too many errors
```

It seems this package would need to migrate from syscall to `"golang.org/x/sys/windows"` and add equivalents for darwin/unix, with build flags.  As a novice it's not clear to me what the equivalents would be for those types.  Could you provide any pointers?

**Comment by morgadow** [comment]
Hey, it seems you are having trouble with your syscall package which is needed to call the pcan dll/dylibs file.
This is required to interact with the PCAN driver itself.

The syscall package should be available under MacOS, but the DLL. Proc and Handle definitions are windows specific.
A compilation selection for different systems would be necessary here.
I can create a new package which is built platform independet and offering a CLI if you want me to?

**Comment by thom-nic** [comment]
Yeah that would be really helpful. Again I'm a golang newbie. When I look at the windows/amd64 context (https://pkg.go.dev/syscall@go1.23.4?GOOS=windows#section-documentation) I see those types but if I switch to linux or darwin context (https://pkg.go.dev/syscall@go1.23.4?GOOS=darwin#section-documentation) those types - Proc, DLL, Handle are not available. So I guess I don't understand how this code is able to build and run under `GOOS=linux` or `GOOS=darwin`?

**Comment by morgadow** [comment]
It seems the problem here is in a change i did some time ago due to problems with the pcan dll handling which requires a windows specific solution. From this point it was not compatible with Mac and linux anymore and the documentation was not updated. 
Give me a couple of days as i have to reinstall virtualbox and everything for testing.

**Comment by thom-nic** [comment]
No problem, again thanks very much for the assistance.

As a learning exercize I tried using cgo.  This appears to work on Darwin after installing the [MacCAN PCUSB library](https://www.mac-can.com/#PCBUSB_lib):
```go

/*
#cgo darwin CFLAGS: -I/usr/local/include
#cgo darwin LDFLAGS: -L/usr/local/lib -lPCBUSB

#include <PCBUSB.h>
*/
import "C"
import (
	"log"
)

func Init() {
	channel := C.TPCANHandle(C.PCAN_USBBUS1)

	stat := C.CAN_Initialize(channel, C.PCAN_BAUD_1M, C.PCAN_USB, 0, 0)
	if stat != C.PCAN_ERROR_OK {
		errMsg, _ := getError(uint32(stat))
		log.Fatalf("Failed to initialize CAN interface: (%d) %s", stat, errMsg)
	}

	log.Println("CAN interface initialized successfully")

	//stat = CAN_GetStatus(channel)

	stat = C.CAN_Reset(channel)

	log.Println("CAN interface reset successfully")
}
```

**Comment by morgadow** [comment]
The cgo approach is interesting but has some limitations for me therefore i did not try it beforehand.
I set up a smaller project only for PCAN and not as a bigger abstraction for different CAN hardware vendors: https://github.com/morgadow/gopcan 
This is currently only for windows but includes a CLI, trying to port this also to darwin and linux the upcoming days.

I the future i guess the best compatibility for all platforms can be reached using your cgo approach.

**Comment by thom-nic** [comment]
Hey that's great, thank you, I'll follow that project.  I'm only using the PEAK USB hardware for my application so that's fine.  My primary interest is in being able to send and decode an app-specific set of CAN messages as a developer tool from a Win/ MacOS/ linux host.  Go is an appealing platform to implement this because installing the tool is trivial (a single binary) assuming the driver is already installed.

**Comment by morgadow** [comment]
Hey, happy to hear that project might help. Go is cool for this project, also did this to build a bigger restbussimulation using concurrency. But after some issues with the .dll wrapping i switched to C#.

Tried to compile several cgo projects now but failed. If you would like to make a pull request or fork to this repository please go ahead :)

**Comment by thom-nic** [comment]
Hey that's great, thank you, I'll follow that project.

**Comment by morgadow** [comment]
Ok cool, have fun :)
If you encounter any bugs or issues, please let me know. I will close this issue for the meantime, okay?
